### ISSUE TITLE
I can run eval.py but can't run benchmark.py because of no "xxxx_obj.txt" files

### ISSUE THREAD

**Issue by dedoogong** [j96w/6-PACK#13]
Hello, thank you for sharing this code. 

I could run eval.py on NOCS real_val DB + your custom GT labels. But I got an error when running benchmark.py

No such file or directory: '/data/My_NOCS/data_obj/real_val/scene_4/0000_obj.txt'
I found only xxx.obj files in obj_models folder, not xxx_obj.txt files. what file should I use? and where can I find it?

Please give me any hint.

Thank you.

**Comment by LyuJ1998** [comment]
Hi,
I have fix the bug in `benchmark.py`, now you do not need `*_obj.txt` any more.
Please check it and thanks for mention the bug.
