### ISSUE TITLE
No real_val file.

### ISSUE THREAD

**Issue by foxmari** [j96w/6-PACK#14]
Hi.
Thanks for sharing the code.

In step 1 of the Dataset part of Read me, it said to download four datasets from the NOCS dataset.
However, when I download those four files, I don't have the "real_val" file mentioned in step 2.
Has the dataset been renamed?

CAMERA Dataset Training--------unzip-------→train/
Real Dataset Training--------unzip-------→real_train/
Real Dataset Test --------unzip-------→real_test/
Ground truth pose annotationVal&Real_test--------unzip-------→gts/

**Comment by LyuJ1998** [comment]
Hello,
you can simply rename the `real_test` to the name `real_val`.

**Comment by foxmari** [comment]
！
I see .
Thank you.
