### ISSUE TITLE
something wrong in"My_NOCS/data_list/real_val/2/bowl_white_small_norm/list.txt"

### ISSUE THREAD

**Issue by Liuchongpei** [j96w/6-PACK#16]
![2345截图20200724105810](https://user-images.githubusercontent.com/34116796/88357077-9c5aa580-cd9c-11ea-87bf-60c348016efc.jpg)
"List.txt" contains the path of "0204_meta.txt". The file (**0204_meta.txt**)with serial number 1 in the figure has **5** instances, while the GT file(**results_real_test_scene_1_0204.pkl**) with serial number 2 in the figure has only **4** instances.So this error occurred

0204_meta.txt:
![2345截图20200724103437](https://user-images.githubusercontent.com/34116796/88357195-04a98700-cd9d-11ea-892f-0e3af03a451c.jpg)

print "results_real_test_scene_1_0204.pkl":
![2345截图20200724103327](https://user-images.githubusercontent.com/34116796/88357200-0c692b80-cd9d-11ea-972c-ac13dadef184.jpg)

**Comment by LyuJ1998** [comment]
Hi,
The file `0204_meta.txt` and `results_real_test_scene_1_0204.pkl` are provided by the original [NOCS dataset](https://github.com/hughw19/NOCS_CVPR2019). I have checked it, and found that the object `can_arizona_tea_norm` should not be in this frame, so maybe delete the line `3 4 can_arizona_tea_norm` can solve this error.

**Comment by Liuchongpei** [comment]
Maybe this is not a good solution. I encountered the same problem in the files **My_NOCS/data/real_val/scene_1/0203_meta.txt, 0204_meta.txt, 0198_meta.txt, 0199_meta.txt, 0200_meta.txt**, maybe there are more .

**Comment by LyuJ1998** [comment]
Thanks for mention this, we didn't realize this problem before, it's not something wrong in `list.txt` but the ground-truth. However, the original NOCS dataset only provide `gt_RTs` in `results_*.pkl`, we can only match the data in `*_meta.txt` and `results_*.pkl` according to the order. So if we want to solve this, we have to manually check the data one by one, which is a huge work. We will try to find the author of NOCS to solve this later.

Thank you again for report this error! In this case, wrong ground-truth data will be used in `benchmark.py`,  which means the precision may be higher than we report in paper. We may update the precision on NOCS dataset after fix this error.

**Comment by LyuJ1998** [comment]
Someone else has reported this problem in this  [link](https://github.com/hughw19/NOCS_CVPR2019/issues/21).

**Comment by Liuchongpei** [comment]
Okay thank you.
