### ISSUE TITLE
No _bbox.txt file

### ISSUE THREAD

**Issue by chenerg** [j96w/6-PACK#2]
https://github.com/j96w/6-PACK/blob/f9d09d7d1163af66762b3ca6f878ebdef831506e/dataset/dataset_nocs.py#L280

There is no _bbox.txt file in the original NOCS dataset.

**Comment by LyuJ1998** [comment]
Hi, you can get '_bbox.txt' file from this link: 
https://drive.google.com/drive/folders/1FWNYJ1E7nMJe7FSK_jVD8YsuMrAVhmvJ?usp=sharing

**Comment by j96w** [comment]
Please follow the dataset preparation steps written in README to obtain the same dataset as we do.

**Comment by joy-yjl** [comment]
> Please follow the dataset preparation steps written in README to obtain the same dataset as we do.

There is no _bbox.txt file in NOCS-REAL275-additional.zip, too.

**Comment by lh641446825** [comment]
The folder `data_pose` cannot be placed under `My_NOCS`, otherwise an error will be reported. It needs to be merged with the folder `data`. And the file `bbox.txt` also needs to be placed under `data`, but there is no _bbox.txt file in NOCS-REAL275-additional.zip

**Comment by j96w** [comment]
Hi @chenerg, @joy-yjl, @lh641446825,
We have uploaded our `data_preprocess.py` script in the `6-PACK/dataset/` folder, which is used to generate the `_bbox.txt` files.

Also @lh641446825,
Thanks for mention this dataloader bug. We have fixed this problem by replacing the "data/" with the "data_pose/". Please check it out.

**Comment by foxmari** [comment]
hello
Running data_preprocess.py does not generate the _bbox.txt file.
This mean is "you can export the standard output to text and save it as "_bbox.txt""?

**Comment by LyuJ1998** [comment]
Hi @foxmari 
If you follow the dataset preparation steps written in README and running `data_preprocess.py`, the `*_bbox.txt` will be generated in `My_NOCS/data_pose/train/*/*_bbox.txt`.

But there is something wrong in `dataset/dataset_nocs.py` line 280:
```python
input_file = open('{0}_bbox.txt'.format(choose_frame), 'r')
```
which should be change to:
```python
input_file = open('{0}_bbox.txt'.format(choose_frame.replace("data/", "data_pose/")), 'r')
```
We will fix this bug later, thank you for mention it.

**Comment by foxmari** [comment]
When I read the code, I didn't realize it was replacing path. 

I found the *_bbox.txt file in two places.
- /data_pose/train/*/*_bbox.txt
- /data/train/*/*_bbox.txt

Is this correct?

Thank you!

**Comment by LyuJ1998** [comment]
@foxmari , do you edit the `preprocess.py`? The `*_bbox.txt` file should not be found in `/data/train`, but I think this might have no effect.

**Comment by foxmari** [comment]
Ok, thank you very much.
I did a lot of research before I asked this question, so I may have added a note at that time.
Thank you for letting me know.

**Comment by zuoligang1997** [comment]
> Hi, you can get '_bbox.txt' file from this link:
> https://drive.google.com/drive/folders/1FWNYJ1E7nMJe7FSK_jVD8YsuMrAVhmvJ?usp=sharing

你好，我想在ROS上运行，没看懂那部分介绍，能说的详细点吗？
