### ISSUE TITLE
I can't find the directory: "My_NOCS/data_pose/real_val" ?

### ISSUE THREAD

**Issue by CodeLHY** [j96w/6-PACK#21]
Hi @j96w ,
This is really a nice work, 
But it seems that I can't find the real_val's pose information, in other words, I can't find the directory: "My_NOCS/data_pose/real_val"

**Comment by LyuJ1998** [comment]
Hi, we didn't release the ground truth pose data of 'real_val' split, you can download it from the original NOCS repo(https://github.com/hughw19/NOCS_CVPR2019)

**Comment by CodeLHY** [comment]
Thank you for your reply, it's my mistake. I'll close this issue.

**Comment by sunshantong** [comment]
@CodeLHY Hi, Same problem as you. How did you fix it? Without "My_NOCS/data_pose/real_val", my program will pause at testdataloader.[https://github.com/j96w/6-PACK/issues/23](url) Thank you very much.

**Comment by JiazeWang** [comment]
@CodeLHY Hello, I met the same problem. Could you please tell me how to solve the problem? Thanks for you help!

**Comment by LyuJ1998** [comment]
@sunshantong @JiazeWang 
I have fix the bug, now you can run the code without "My_NOCS/data_pose/real_val".
Please check it!

**Comment by CodeLHY** [comment]
https://github.com/j96w/6-PACK/issues/5#issuecomment-559868155
I'm sorry to reply you so late. Maybe this will help you.
