### ISSUE TITLE
How to get the real_val pose???

### ISSUE THREAD

**Issue by JiazeWang** [j96w/6-PACK#24]
I fix the bugs following the previous ISSUEs, however, it still occurs:

FileNotFoundError: [Errno 2] No such file or directory: 'My_NOCS/data_pose/real_val/scene_3/0515_pose.txt'

I wonder how to get the pose.txt of real_val. Cause there is no data_pose/real_val in https://github.com/hughw19/NOCS_CVPR2019 or NOCS-REAL275-additional.zip.

Thanks for your kind help! @j96w @LyuJ1998

**Comment by LyuJ1998** [comment]
Hi, thanks for mention this!
I have fix the bug in dataloader, so now you don`t need "My_NOCS/data_pose/real_val/scene_*/*_pose.txt" file anymore.
Please check it!
