### ISSUE TITLE
Where is the rgb/***.png and depth/***.npy data for inference.py?

### ISSUE THREAD

**Issue by foxmari** [j96w/6-PACK#26]
Hello.
I'm trying to get inference.py to work.

I would like a sample of the data you are using in lines 31 and 32（in  inference.py）, is there somewhere I can find it?
Data used in rgb/***.png and depth/***.npy.

**Comment by foxmari** [comment]
I decided to use the same data as eval.py.

I can use this
https://github.com/hughw19/NOCS_CVPR2019 in real_test dataset (http://download.cs.stanford.edu/orion/nocs/real_test.zip)

**Comment by sunshantong** [comment]
@foxmari Hi, sorry to bother you. Do you know how to get the initial pose and scale of the object?
