### ISSUE TITLE
pose information for real_val

### ISSUE THREAD

**Issue by mymrblack** [j96w/6-PACK#5]
Hi, thanks for sharing the code. 

I tried to run the `benchmark.py` but it requires pose information in `real_val/scene_*/` dictionary. I downloaded `NOCS-REAL275-additional.zip`, but it seems that it only contains pose information for real_train dataset. 

Could you share the pose information for real_val dataset or could you tell me how can I get the information by myself? 

Thank you so much!

**Comment by j96w** [comment]
Hi,
The `real_val/scene_*/` could be found at the [original NOCS dataset](https://github.com/hughw19/NOCS_CVPR2019). In their README Datasets section, you could found `Real Dataset: Test`.

**Comment by mymrblack** [comment]
Hi, I downloaded the `Real Dataset: Test` dataset from NOCS, but I can not find `*_pose.txt` file which required in `benchmark.py`:

```python
 gt_path = img_path + "_pose.txt"
```

The file types in the dataset are: `*_color.png`  `*_coord.png`  `*_depth.png`  `*_mask.png`  `*_meta.txt`.

**Comment by lx935484038** [comment]
Hi, I have the same problem with pose information for real_val.  when I run the  train.py, it  can't find file *_pose.txt in My_NOCS/data/real_val/scene_*/. Can` you tell me how did you solve the problem?
Thank you very much!

**Comment by mymrblack** [comment]
> Hi, I have the same problem with pose information for real_val. when I run the train.py, it can't find file __pose.txt in My_NOCS/data/real_val/scene__/. Can` you tell me how did you solve the problem?
> Thank you very much!

Hi, please check with the `MyNOCS/data_pose` folder, copy the `_pose.txt` files into corresponding folders under `My_NOCS/data/`. Hope this helps : )

**Comment by lx935484038** [comment]
Hi, I rechecked the `My_NOCS/data_pose` folder, but there is only `train/` floder and 'real_train/' floder. So, I can't find the corresponding pose floder for `My_NOCS/data/real_veal/`

**Comment by sunshantong** [comment]
> Hi, I rechecked the `My_NOCS/data_pose` folder, but there is only `train/` floder and 'real_train/' floder. So, I can't find the corresponding pose floder for `My_NOCS/data/real_veal/`

Hi, I also encountered the same problem as you. Have you solved it? Thank you very much.

**Comment by sunshantong** [comment]
> > Hi, I have the same problem with pose information for real_val. when I run the train.py, it can't find file **pose.txt in My_NOCS/data/real_val/scene**/. Can` you tell me how did you solve the problem?
> > Thank you very much!
> 
> Hi, please check with the `MyNOCS/data_pose` folder, copy the `_pose.txt` files into corresponding folders under `My_NOCS/data/`. Hope this helps : )

Hi, If it is copying the `_pose.txt` files into corresponding folders, does this mean that _real_val_ and _real_train_ are the same? Thank you so much.

**Comment by lx935484038** [comment]
> > > Hi, I have the same problem with pose information for real_val. when I run the train.py, it can't find file **pose.txt in My_NOCS/data/real_val/scene**/. Can` you tell me how did you solve the problem?
> > > Thank you very much!
> > 
> > 
> > Hi, please check with the `MyNOCS/data_pose` folder, copy the `_pose.txt` files into corresponding folders under `My_NOCS/data/`. Hope this helps : )
> 
> Hi, If it is copying the `_pose.txt` files into corresponding folders, does this mean that _real_val_ and _real_train_ are the same? Thank you so much.

Hi，I also tried this, but found that the two folders are different. I remember that real_train and real_val folders contain different content

**Comment by sunshantong** [comment]
> > > > Hi, I have the same problem with pose information for real_val. when I run the train.py, it can't find file **pose.txt in My_NOCS/data/real_val/scene**/. Can` you tell me how did you solve the problem?
> > > > Thank you very much!
> > > 
> > > 
> > > Hi, please check with the `MyNOCS/data_pose` folder, copy the `_pose.txt` files into corresponding folders under `My_NOCS/data/`. Hope this helps : )
> > 
> > 
> > Hi, If it is copying the `_pose.txt` files into corresponding folders, does this mean that _real_val_ and _real_train_ are the same? Thank you so much.
> 
> Hi，I also tried this, but found that the two folders are different. I remember that real_train and real_val folders contain different content

Thank you for your answer. Yes, it should not be the same. Looking forward to the author's update.

**Comment by JiazeWang** [comment]
> > > > > Hi, I have the same problem with pose information for real_val. when I run the train.py, it can't find file **pose.txt in My_NOCS/data/real_val/scene**/. Can` you tell me how did you solve the problem?
> > > > > Thank you very much!
> > > > 
> > > > 
> > > > Hi, please check with the `MyNOCS/data_pose` folder, copy the `_pose.txt` files into corresponding folders under `My_NOCS/data/`. Hope this helps : )
> > > 
> > >  
> > > Hi, If it is copying the `_pose.txt` files into corresponding folders, does this mean that _real_val_ and _real_train_ are the same? Thank you so much.
> > 
> > 
> > Hi，I also tried this, but found that the two folders are different. I remember that real_train and real_val folders contain different content
> 
> Thank you for your answer. Yes, it should not be the same. Looking forward to the author's update.

Hello, I found I meet the same problem now. Could you please tell me how to find the pose information for real_val?

Thanks again for your kind help!
