### ISSUE TITLE
AttributeError: 'Loss' object has no attribute 'pconf2'

### ISSUE THREAD

**Issue by mymrblack** [j96w/6-PACK#6]
Hi, I am trying to run `inference.py`, but met with an error:

```python
AttributeError: 'Loss' object has no attribute 'pconf2'
```

It comes from `loss.py`, line 262:

```python
new_t = torch.sum(Kp_fr * self.pconf2, dim=1).view(1, 3).contiguous()
```

`self.pconf2` could not be found. 

I saw there is a `self.pconf` in `__init__`, dose line 262 should be change to `self.pconf`?

**Comment by j96w** [comment]
Hi, thanks for mention this bug. We have fixed it in the latest update. Please check it out.

**Comment by mymrblack** [comment]
Thank you.

**Comment by mymrblack** [comment]
> Hi, thanks for mention this bug. We have fixed it in the latest update. Please check it out.

Thank you.
