### ISSUE TITLE
Update of current_t and current_r

### ISSUE THREAD

**Issue by mymrblack** [j96w/6-PACK#8]
Hi, thank you for sharing the code. I am trying to run the code on my computer. I met some problem when I trying to understand the code. 

In the `line 112` of `tracker.py`, it use 'self.Kp_fr' and `Kp_to[idx]` to get the change of pose between keypoints of `first frame` and keypoints of `current frame` (they are `new_t` and `new_r` in the following code). `self.Kp_fr` is the keypoints of first frame because it haven't been changed since the first frame had been processed. Then the code use the pose of `last frame` (`current_t` and `current_t` in the code) and `new_t` and `new_r` to get the pose of `current frame`. Am I right about the code? 

```python
        self.min_dis = 1000.0
        lenggth = len(Kp_to)
        for idx in range(lenggth):
            new_r, new_t, kp_dis = self.criterion.inf(self.Kp_fr, Kp_to[idx])
            if self.min_dis > kp_dis:
                self.min_dis = kp_dis
                best_r = new_r
                best_t = new_t
        print(self.min_dis)

        current_t = current_t + np.dot(best_t, current_r.T)
        current_r = np.dot(current_r, best_r)
        current_t = self.init_t + np.dot(best_t, self.init_r.T)
        current_r = np.dot(self.init_r, best_r
```
Should the `self.Kp_to` be changed to the keypoints of `last frame`?

**Comment by Noone65536** [comment]
I have the same question. Did you find out why?
